contao:
  image:
    sizes:
      example:
        resize_mode: crop
        zoom: 100
        lazy_loading: true
        width: 1920
        height: 1920
        formats:
          jpeg: [webp]
          png: [webp]
  url_suffix: ""
