contao:
  url_suffix: ""
  image:
    sizes:
      example:
        lazy_loading: true
        width: 1000
        height: 1000
        formats:
          jpeg: [webp]
          png: [webp]
          jpg: [webp]
